// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module("NFLHistory");

  app.controller("CoachesCtrl", function($scope, NFLdata, Plot) {
    Plot.plotGrid();
    $scope.coaches = NFLdata.getCoaches();
    $scope.selectedCoach = null;
    $scope.selectCoach = function(coachID) {
      console.log("Selected Coach " + coachID);
      $scope.selectedCoach = coachID;
      return Plot.plotCoach(this.coach);
    };
    $scope.getAssociates = function() {
      var associates;
      associates = NFLdata.getAssociates($scope.selectedCoach);
      console.log("Associates " + associates);
      return Plot.plotAssociates($scope.coaches, associates);
    };
    return $scope.erasePlot = function() {
      return Plot.erasePlot();
    };
  });

}).call(this);
