// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return console.log("jQuery is in the house");
    /*
    	
    
    	allCoaches = coaches.getCoaches()
    	
    	for coach, i in allCoaches
    		console.log "#{i}: #{coach.name}"
    		if coach.name is "Sean Payton"
    			plotCoach(coach)
    	
    	##plotCoach(allCoaches[124])
    */

  });

}).call(this);
